export const SET_USER = 'SET_USER';
export const SET_ORGANIZATION = 'SET_ORGANIZATION';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_FEATURES = 'SET_FEATURES';
export const SET_EFFORT_ESTIMATIONS = 'SET_EFFORT_ESTIMATIONS';
export const CLEAR_PLANNING = 'CLEAR_PLANNING';
export const SET_COMMENTS = 'SET_COMMENTS';
